
env:
  CI: false
on: 
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev
name: ğŸš€ Deploy Tropa Digital
jobs:
  web-deploy:
    name: ğŸ‰ Baixando Dependencias no servidor
    runs-on: ubuntu-latest
    steps:
    - name: ğŸšš Baixando ultima versÃ£o do cÃ³digo
      uses: actions/checkout@v2
      

    - name: Usando Node.js 14
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: ğŸ”¨ Instalando Dependencias
      run: npm install
    - name: ğŸ”¨ Instalando build
      run: npm run build
    - name: ğŸ”— Iniciando conexÃ£o FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: tropadigital.virtuaserver.com.br
        username: admin
        password: xpIB7Q9Ft9h4g77
        server-dir: /domains/backendtropa.com.br/public_html/tradicao/
